# https://raw.githubusercontent.com/rubocop-hq/rubocop/master/config/default.yml

AllCops:
  Include:
    - gems.rb
    - '**/*.rb'
    - '**/*.arb'
    - '**/*.axlsx'
    - '**/*.builder'
    - '**/*.fcgi'
    - '**/*.gemspec'
    - '**/*.god'
    - '**/*.jb'
    - '**/*.jbuilder'
    - '**/*.mspec'
    - '**/*.opal'
    - '**/*.pluginspec'
    - '**/*.podspec'
    - '**/*.rabl'
    - '**/*.rake'
    - '**/*.rbuild'
    - '**/*.rbw'
    - '**/*.rbx'
    - '**/*.ru'
    - '**/*.ruby'
    - '**/*.spec'
    - '**/*.thor'
    - '**/*.watchr'
    - '**/.irbrc'
    - '**/.pryrc'
    - '**/buildfile'
    - '**/config.ru'
    - '**/Appraisals'
    - '**/Berksfile'
    - '**/Brewfile'
    - '**/Buildfile'
    - '**/Capfile'
    - '**/Cheffile'
    - '**/Dangerfile'
    - '**/Deliverfile'
    - '**/Fastfile'
    - '**/*Fastfile'
    - '**/Guardfile'
    - '**/Jarfile'
    - '**/Mavenfile'
    - '**/Podfile'
    - '**/Puppetfile'
    - '**/Rakefile'
    - '**/Snapfile'
    - '**/Thorfile'
    - '**/Vagabondfile'
    - '**/Vagrantfile'
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - '.git/**/*'
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

# Checks for missing top-level documentation of classes and modules
Documentation:
  Enabled: false

# Checks whether the source file has a utf-8 encoding comment or not
Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# There is an issue with the Enumerize gem
# Use #value? instead of #values.include?.
# `assert Request.request_type.values.include?(@request.request_type)`
Performance/InefficientHashSearch:
    Enabled: false

Metrics/BlockLength:
  Exclude:
    - "app/admin/**/*.rb"
